language: node_js

node_js:
  - 'node'

sudo: required

# Skip install process.  Everything will be done in Docker.
install: true

services:
  - docker

script:
  - yarn lint
  - docker-compose build
  - docker-compose run app yarn test
