version: '2'
services:
  app:
    build: .
    links:
      - elasticsearch
      - rethinkdb

  elasticsearch:
    environment:
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    mem_limit: 2g
    ports:
      - 9200:9200

  rethinkdb:
    image: rethinkdb:latest
    ports:
      - 8080:8080
      - 28015:28015
