version: '2'
services:
  app:
    build: .
    links:
      - elasticsearch
      - rethinkdb

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    ports:
      - 9200:9200

  rethinkdb:
    image: rethinkdb:latest
    ports:
      - 28015:28015
